[package]
description = "`span` is a region of source code"
documentation = "https://docs.rs/parserc-span"
edition = "2024"
license = "MIT"
name = "parserc-span"
repository = "https://github.com/markdown-labs/parserc/crates/span"
version.workspace = true

[dependencies]
