[package]
description = "Parser combinator for `rust` language."
documentation = "https://docs.rs/parserc"
edition = "2024"
license = "MIT"
name = "parserc"
repository = "https://github.com/markdown-labs/parserc"
version.workspace = true


[dependencies]
thiserror = "2.0.17"
sourcespan = { version = "^0.10", path = "../span" }
memchr = { version = "2.7.6", optional = true }
serde = { version = "1.0.228", optional = true }

[features]
default = ["lang","serde","syntax"]
lang = ["memchr"]
serde = ["dep:serde","serde/derive", "sourcespan/serde"]
syntax = []
